# Generated by Django 4.1.5 on 2023-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Unique', models.IntegerField(default='')),
                ('Contact', models.IntegerField(default='')),
                ('Address', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
